version: '2'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: ombusite
    expose:
      - "3306"
    ports:
      - "3306:3306"
  web:
    build:
      context: ./..
      dockerfile: docker/Dockerfile.devel
    ports:
      - "80:8000"
    links:
      - db
    volumes:
      - ./..:/var/www/ombusite.local
  gulp:
    image: node:4
    command: bash -c "cd /var/www/ombusite.local/website/static/website && npm install && npm start"
    volumes:
      - ./../website/static/website:/var/www/ombusite.local/website/static/website
