#!/usr/bin/env bash

#############################
# START OF USER CONFIGURATION
#############################

# Global
ARCH_SLUG=ombusite

# Environment specific variables
INFRASTRUCTURE_STACK_staging=ombu-services-development-1810311008
INFRASTRUCTURE_STACK_production=ombu-services-development-1810311008
SERVICES_STACK_staging=ombusite-staging-1902091650
SERVICES_STACK_production=ombusite-production-1902091658

###########################
# END OF USER CONFIGURATION
###########################

aws="docker run --rm -v ${PWD}:/tmp -w /tmp -e AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY -e AWS_DEFAULT_REGION ombu/docker-awscli aws"

if [[ -z ${SKIP_ENVIRONMENT_CHECK} ]]
then
    appEnv=$1
    if [[ "${appEnv}" != "staging" ]] && [[ "${appEnv}" != "production" ]]
    then
        echo "Unknown environment ${appEnv}"
        echo "The known environments are: staging, production"
        exit 1
    fi
fi

# Convenience variables for scripts that source this one
_infrastructure_stack_name=INFRASTRUCTURE_STACK_${appEnv}
infrastructure_stack_name=${!_infrastructure_stack_name}
_services_stack_name=SERVICES_STACK_${appEnv}
services_stack_name=${!_services_stack_name}
