#!/usr/bin/env bash

#############################
# START OF USER CONFIGURATION
#############################

# Global
ARCH_SLUG=ombusite

# Environment specific variables
INFRASTRUCTURE_STACK_staging=ombu-services-development-1810311008
INFRASTRUCTURE_STACK_production=ombu-services-development-1810311008
APPLICATION_STACK_staging=ombusite-application-staging-1902101607
APPLICATION_STACK_production=
PIPELINE_STACK_staging=ombusite-pipeline-staging-1902101609
PIPELINE_STACK_production=

###########################
# END OF USER CONFIGURATION
###########################

aws="docker run --rm -v ${PWD}:/tmp -w /tmp -e AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY -e AWS_DEFAULT_REGION ombu/docker-awscli aws"

appEnv=$1
if [[ -z ${SKIP_ENVIRONMENT_CHECK} ]]
then
    if [[ "${appEnv}" != "staging" ]] && [[ "${appEnv}" != "production" ]]
    then
        echo "Unknown environment ${appEnv}"
        echo "The known environments are: staging, production"
        exit 1
    fi
fi

component=$2
if [[ -n ${VALIDATE_COMPONENT} ]]
then
    if [[ "${component}" != "application" ]] && [[ "${component}" != "pipeline" ]]
    then
        echo "Unknown stack component ${component}"
        echo "The known components are: application, pipeline"
        exit 1
    fi
fi

# Convenience variables for scripts that source this one
_infrastructure_stack_name=INFRASTRUCTURE_STACK_${appEnv}
infrastructure_stack_name=${!_infrastructure_stack_name}
_application_stack_name=APPLICATION_STACK_${appEnv}
application_stack_name=${!_application_stack_name}
_pipeline_stack_name=PIPELINE_STACK_${appEnv}
pipeline_stack_name=${!_pipeline_stack_name}

parameters="ParameterKey=EnvironmentType,ParameterValue=${appEnv} ParameterKey=InfrastructureStack,ParameterValue=${infrastructure_stack_name}"

#if [[ "$component" == 'application' ]] ; then
#fi
if [[ "$component" == 'pipeline' ]] ; then
    parameters="$parameters ParameterKey=ApplicationStack,ParameterValue=${application_stack_name}"
fi
