#!/usr/bin/env bash

set -e

if [[ -n $2 ]]
then
    echo "Too many arguments were provided."
    echo "Usage build-remote-images <tag>"
    exit 1
fi


tag=$1
if [[ -z ${tag} ]]
then
    echo "No tag provided."
    echo "Usage build-remote-images <tag>"
    exit 1
fi

script_path="$(cd "$(dirname "$0")" && pwd)"
SKIP_ENVIRONMENT_CHECK=1 source ${script_path}/_env

printf "Determining AWS account id: "
awsAccountId=`${aws} sts get-caller-identity --query Account --output text`
printf "${awsAccountId}\n"

TAG=${tag} AWS_ACCOUNT_ID=${awsAccountId} docker-compose -f infrastructure/docker-compose.yml build 1>/dev/null
eval $(${aws} ecr get-login --no-include-email)
TAG=${tag} AWS_ACCOUNT_ID=${awsAccountId} docker-compose -f infrastructure/docker-compose.yml push 1>/dev/null

exit 0
