#!/usr/bin/env bash
set -e

script_path="$(cd "$(dirname "$0")" && pwd)"
source ${script_path}/_env

if [[ "$component" == 'application' ]]; then
    stack_name=${application_stack_name}
elif [[ "$component" == 'pipeline' ]]; then
    stack_name=${pipeline_stack_name}
fi

source ${script_path}/stack-package ${appEnv}

echo "Updating stack: ${stack_name}"
${aws} cloudformation update-stack \
    --stack-name ${stack_name} \
    --template-body file://build/packaged_${component}_${appEnv}.yaml \
    --capabilities CAPABILITY_NAMED_IAM \
    --parameters ${parameters}
${aws} cloudformation wait stack-update-complete --stack-name ${stack_name}
