#!/usr/bin/env bash
set -e

script_path="$(cd "$(dirname "$0")" && pwd)"
source ${script_path}/_env

stack_name=${ARCH_SLUG}-${appEnv}-`date '+%y%m%d%H%M'`

source ${script_path}/stack-package ${appEnv}

echo "Launching stack: ${stack_name}"
${aws} cloudformation create-stack \
    --disable-rollback \
    --stack-name ${stack_name} \
    --template-body file://build/packaged_${appEnv}.yaml \
    --capabilities CAPABILITY_NAMED_IAM \
    --parameters ParameterKey=EnvironmentType,ParameterValue=${appEnv} \
                 ParameterKey=InfrastructureStack,ParameterValue=${infrastructure_stack_name}
